import type { StencilLibraryDef } from '../types.js';
import { registerLibrary } from '../registry.js';

const AWS4_CATEGORY_COLORS: Record<string, string> = {
  general: '#232F3D',
  compute: '#ED7100',
  storage: '#3F8624',
  database: '#C925D1',
  networking: '#8C4FFF',
  analytics: '#6A39B7',
  security: '#DD344C',
  management: '#E7157B',
  integration: '#34A1C1',
  app_integration: '#DD344C',
  ml: '#01A88D',
  media: '#1D9ACA',
  migration: '#4D72B3',
  developer: '#2FCE96',
  end_user_computing: '#7AA116',
  game: '#7AA116',
  iot: '#3F362F',
  mobile: '#7AA116',
  blockchain: '#7AA116',
  satellite: '#2FCE96',
  quantum: '#8C4FFF',
  robotics: '#7AA116',
  customer_enablement: '#7AA116',
};

function s(name: string, category: string, variant: 'resourceIcon' | 'direct' = 'resourceIcon') {
  return { name, category, color: AWS4_CATEGORY_COLORS[category] ?? '#232F3D', variant };
}

export const aws4Library: StencilLibraryDef = {
  id: 'aws4',
  name: 'AWS 2021+',
  prefix: 'mxgraph.aws4',
  shapes: {
    // ── Compute ──────────────────────────────────────────────
    ec2: s('ec2', 'compute'),
    lambda: s('lambda', 'compute', 'direct'),
    fargate: s('fargate', 'compute'),
    ecs: s('ecs', 'compute'),
    eks: s('eks', 'compute'),
    batch: s('batch', 'compute'),
    lightsail: s('lightsail', 'compute'),
    elastic_beanstalk: s('elastic_beanstalk', 'compute'),
    auto_scaling: s('auto_scaling', 'compute'),
    outposts: s('outposts', 'compute'),
    ec2_image_builder: s('ec2_image_builder', 'compute'),
    vmware_cloud_on_aws: s('vmware_cloud_on_aws', 'compute'),
    elastic_kubernetes_service: s('elastic_kubernetes_service', 'compute'),

    // ── Storage ──────────────────────────────────────────────
    s3: s('s3', 'storage'),
    ebs: s('ebs', 'storage'),
    efs: s('efs', 'storage'),
    fsx: s('fsx', 'storage'),
    glacier: s('glacier', 'storage'),
    backup: s('backup', 'storage'),
    storage_gateway: s('storage_gateway', 'storage'),
    s3_glacier: s('s3_glacier', 'storage'),
    snowball: s('snowball', 'storage'),
    aws_backup: s('aws_backup', 'storage'),

    // ── Database ─────────────────────────────────────────────
    rds: s('rds', 'database'),
    dynamodb: s('dynamodb', 'database'),
    aurora: s('aurora', 'database'),
    redshift: s('redshift', 'database'),
    elasticache: s('elasticache', 'database'),
    neptune: s('neptune', 'database'),
    documentdb_with_mongodb_compatibility: s('documentdb_with_mongodb_compatibility', 'database'),
    keyspaces: s('keyspaces', 'database'),
    dynamodb_accelerator_dax: s('dynamodb_accelerator_dax', 'database'),
    database_migration_service: s('database_migration_service', 'database'),
    timestream: s('timestream', 'database'),
    quantum_ledger_database_qldb: s('quantum_ledger_database_qldb', 'database'),

    // ── Networking ───────────────────────────────────────────
    vpc: s('vpc', 'networking'),
    cloudfront: s('cloudfront', 'networking'),
    route_53: s('route_53', 'networking'),
    api_gateway: s('api_gateway', 'networking'),
    elastic_load_balancing: s('elastic_load_balancing', 'networking'),
    direct_connect: s('direct_connect', 'networking'),
    transit_gateway: s('transit_gateway', 'networking'),
    nat_gateway: s('nat_gateway', 'networking'),
    vpn_connection: s('vpn_connection', 'networking'),
    internet_gateway: s('internet_gateway', 'networking'),
    cloud_wan: s('cloud_wan', 'networking'),
    global_accelerator: s('global_accelerator', 'networking'),
    privatelink: s('privatelink', 'networking'),
    vpc_peering: s('vpc_peering', 'networking'),
    aws_private_5g: s('aws_private_5g', 'networking'),
    client_vpn: s('client_vpn', 'networking'),
    site_to_site_vpn: s('site_to_site_vpn', 'networking'),
    aws_app_mesh: s('aws_app_mesh', 'networking'),
    cloud_map: s('cloud_map', 'networking'),
    elastic_ip_address: s('elastic_ip_address', 'networking'),

    // ── Security ─────────────────────────────────────────────
    identity_and_access_management: s('identity_and_access_management', 'security'),
    key_management_service: s('key_management_service', 'security'),
    guardduty: s('guardduty', 'security'),
    shield: s('shield', 'security'),
    waf: s('waf', 'security'),
    inspector: s('inspector', 'security'),
    secrets_manager: s('secrets_manager', 'security'),
    certificate_manager: s('certificate_manager', 'security'),
    cognito: s('cognito', 'security'),
    directory_service: s('directory_service', 'security'),
    aws_firewall_manager: s('aws_firewall_manager', 'security'),
    artifact: s('artifact', 'security'),
    macie: s('macie', 'security'),
    security_hub: s('security_hub', 'security'),
    detective: s('detective', 'security'),
    aws_signer: s('aws_signer', 'security'),

    // ── Analytics ────────────────────────────────────────────
    athena: s('athena', 'analytics'),
    emr: s('emr', 'analytics'),
    glue: s('glue', 'analytics'),
    kinesis: s('kinesis', 'analytics'),
    quicksight: s('quicksight', 'analytics'),
    lake_formation: s('lake_formation', 'analytics'),
    opensearch_service: s('opensearch_service', 'analytics'),
    redshift_spectrum: s('redshift_spectrum', 'analytics'),
    aws_data_pipeline: s('aws_data_pipeline', 'analytics'),
    kinesis_data_streams: s('kinesis_data_streams', 'analytics'),
    kinesis_data_firehose: s('kinesis_data_firehose', 'analytics'),
    managed_streaming_for_apache_kafka: s('managed_streaming_for_apache_kafka', 'analytics'),

    // ── Machine Learning ─────────────────────────────────────
    sagemaker: s('sagemaker', 'ml'),
    bedrock: s('bedrock', 'ml'),
    comprehend: s('comprehend', 'ml'),
    rekognition: s('rekognition', 'ml'),
    polly: s('polly', 'ml'),
    transcribe: s('transcribe', 'ml'),
    translate: s('translate', 'ml'),
    textract: s('textract', 'ml'),
    lex: s('lex', 'ml'),
    deepracer: s('deepracer', 'ml'),
    forecast: s('forecast', 'ml'),
    personalize: s('personalize', 'ml'),
    aws_deep_learning_amis: s('aws_deep_learning_amis', 'ml'),
    comprehend_medical: s('comprehend_medical', 'ml'),

    // ── Management & Governance ──────────────────────────────
    cloudformation: s('cloudformation', 'management'),
    cloudwatch: s('cloudwatch', 'management'),
    cloudtrail: s('cloudtrail', 'management'),
    config: s('config', 'management'),
    systems_manager: s('systems_manager', 'management'),
    organizations: s('organizations', 'management'),
    control_tower: s('control_tower', 'management'),
    trusted_advisor: s('trusted_advisor', 'management'),
    auto_scaling_group: s('auto_scaling_group', 'management'),
    aws_health_dashboard: s('aws_health_dashboard', 'management'),
    service_catalog: s('service_catalog', 'management'),
    aws_chatbot: s('aws_chatbot', 'management'),
    aws_well_architected_tool: s('aws_well_architected_tool', 'management'),
    aws_launch_wizard: s('aws_launch_wizard', 'management'),

    // ── Application Integration ──────────────────────────────
    sqs: s('sqs', 'integration'),
    sns: s('sns', 'integration'),
    eventbridge: s('eventbridge', 'integration'),
    step_functions: s('step_functions', 'integration'),
    appflow: s('appflow', 'integration'),
    mq: s('mq', 'integration'),
    aws_lambda: s('aws_lambda', 'integration'),

    // ── Developer Tools ──────────────────────────────────────
    codecommit: s('codecommit', 'developer'),
    codebuild: s('codebuild', 'developer'),
    codedeploy: s('codedeploy', 'developer'),
    codepipeline: s('codepipeline', 'developer'),
    codeartifact: s('codeartifact', 'developer'),
    cloud9: s('cloud9', 'developer'),
    x_ray: s('x_ray', 'developer'),
    codewhisperer: s('codewhisperer', 'developer'),
    tools_and_sdks: s('tools_and_sdks', 'developer'),

    // ── Migration ────────────────────────────────────────────
    database_migration_service_dms: s('database_migration_service_dms', 'migration'),
    datasync: s('datasync', 'migration'),
    transfer_family: s('transfer_family', 'migration'),
    aws_migration_hub: s('aws_migration_hub', 'migration'),
    application_migration_service: s('application_migration_service', 'migration'),
    application_discovery_service: s('application_discovery_service', 'migration'),
    aws_server_migration_service: s('aws_server_migration_service', 'migration'),

    // ── IoT ──────────────────────────────────────────────────
    iot_core: s('iot_core', 'iot'),
    iot_analytics: s('iot_analytics', 'iot'),
    iot_events: s('iot_events', 'iot'),
    greengrass: s('greengrass', 'iot'),
    iot_device_management: s('iot_device_management', 'iot'),
    iot_device_defender: s('iot_device_defender', 'iot'),
    iot_sitewise: s('iot_sitewise', 'iot'),

    // ── Media Services ───────────────────────────────────────
    elemental_mediaconvert: s('elemental_mediaconvert', 'media'),
    elemental_medialive: s('elemental_medialive', 'media'),
    elemental_mediapackage: s('elemental_mediapackage', 'media'),
    elemental_mediastore: s('elemental_mediastore', 'media'),
    elemental_mediatailor: s('elemental_mediatailor', 'media'),
    kinesis_video_streams: s('kinesis_video_streams', 'media'),

    // ── End User Computing ───────────────────────────────────
    workspaces: s('workspaces', 'end_user_computing'),
    appstream_2: s('appstream_2', 'end_user_computing'),
    worklink: s('worklink', 'end_user_computing'),

    // ── Blockchain ───────────────────────────────────────────
    managed_blockchain: s('managed_blockchain', 'blockchain'),
    quantum_ledger_database: s('quantum_ledger_database', 'blockchain'),

    // ── Satellite ────────────────────────────────────────────
    ground_station: s('ground_station', 'satellite'),

    // ── General / Misc ───────────────────────────────────────
    management_console: s('management_console', 'general'),
    cli: s('cli', 'general'),
    sdk: s('sdk', 'general'),
    aws_costs_and_usage_report: s('aws_costs_and_usage_report', 'general'),
    customer: s('customer', 'general'),
    forum: s('forum', 'general'),
    generic_database: s('generic_database', 'general'),
    generic_firewall: s('generic_firewall', 'general'),
    generic_internet: s('generic_internet', 'general'),
    generic_server: s('generic_server', 'general'),
    mobile_client: s('mobile_client', 'general'),
    multicast: s('multicast', 'general'),
    office_building: s('office_building', 'general'),
    user: s('user', 'general'),
    users: s('users', 'general'),
    traditional_server: s('traditional_server', 'general'),
    tape_storage: s('tape_storage', 'general'),
  },
  groups: {
    aws_cloud: { name: 'aws_cloud', fillColor: 'none', strokeColor: '#232F3D' },
    aws_cloud_alt: { name: 'aws_cloud_alt', fillColor: 'none', strokeColor: '#232F3D' },
    region: { name: 'region', fillColor: 'none', strokeColor: '#8C4FFF' },
    vpc: { name: 'vpc', fillColor: 'none', strokeColor: '#8C4FFF' },
    vpc2: { name: 'vpc2', fillColor: 'none', strokeColor: '#8C4FFF' },
    availability_zone: { name: 'availability_zone', fillColor: 'none', strokeColor: '#8C4FFF' },
    subnet: { name: 'subnet', fillColor: 'none', strokeColor: '#8C4FFF' },
    security_group: { name: 'security_group', fillColor: 'none', strokeColor: '#DD344C' },
    auto_scaling_group: { name: 'auto_scaling_group', fillColor: 'none', strokeColor: '#ED7100' },
    corporate_data_center: { name: 'corporate_data_center', fillColor: 'none', strokeColor: '#232F3D' },
    elastic_beanstalk: { name: 'elastic_beanstalk', fillColor: 'none', strokeColor: '#ED7100' },
    spot_fleet: { name: 'spot_fleet', fillColor: 'none', strokeColor: '#ED7100' },
    elastic_load_balancing: { name: 'elastic_load_balancing', fillColor: 'none', strokeColor: '#8C4FFF' },
    on_premise: { name: 'on_premise', fillColor: 'none', strokeColor: '#232F3D' },
    iot_greengrass: { name: 'iot_greengrass', fillColor: 'none', strokeColor: '#3F362F' },
    iot_greengrass_deployment: { name: 'iot_greengrass_deployment', fillColor: 'none', strokeColor: '#3F362F' },
  },
  resourceIconStyle: 'sketch=0;outlineConnect=0;fontColor=#232F3E;fillColor={COLOR};strokeColor=#ffffff;dashed=0;verticalLabelPosition=bottom;verticalAlign=top;align=center;html=1;fontSize=12;fontStyle=0;aspect=fixed;shape={PREFIX}.resourceIcon;resIcon={PREFIX}.{SHAPE};',
  directStyle: 'sketch=0;outlineConnect=0;fontColor=#232F3E;gradientColor=none;fillColor={COLOR};strokeColor=none;dashed=0;verticalLabelPosition=bottom;verticalAlign=top;align=center;html=1;fontSize=12;fontStyle=0;aspect=fixed;pointerEvents=1;shape={PREFIX}.{SHAPE};',
  groupStyle: 'outlineConnect=0;gradientColor=none;html=1;whiteSpace=wrap;fontSize=12;fontStyle=0;container=1;pointerEvents=0;collapsible=0;recursiveResize=0;shape={PREFIX}.group;grIcon={PREFIX}.group_{GROUP};strokeColor={STROKE};fillColor=none;verticalAlign=top;align=left;spacingLeft=30;fontColor={STROKE};dashed=0;',
};

registerLibrary(aws4Library);
